<?php

use Illuminate\Database\Seeder;

class SpecificationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('specification')->insert(array(
            array(
                'id'=>'1',
                'pic1'=>'../assets/image/catalogotelefoni/samsungs9/2.jpeg',
                'pic2'=>'../assets/image/catalogotelefoni/samsungs9/3.jpeg',
                'pic3'=>'../assets/image/catalogotelefoni/samsungs9/4.jpeg',
                'brand'=>'Samsung',
                'model'=>'S9',
                'weight'=>'1.92',
                'year'=>'2018',
                'memory'=>'128 Gb',
                'system'=>'Andorid 8.1',
                'processor'=>'4x 2.8 GHz M3 Mongoose + 4x 1.7 GHz Cortex-A55',
                'screen'=>'5.8',
                'display'=>'Super AMOLED',
                'resolution'=>'1440 x 2960 pixel',
                'camera'=>'12 Mp',
                'price'=>'899',
                'color' => 'black',
                'status' => 'nuovo',
            ),array(
                'id'=>'2',
                'pic1'=>'../assets/image/catalogotelefoni/samsungs8+/1.jpeg',
                'pic2'=>'../assets/image/catalogotelefoni/samsungs8+/2.jpeg',
                'pic3'=>'../assets/image/catalogotelefoni/samsungs8+/3.jpeg',
                'brand'=>'Samsung',
                'model'=>'S8+',
                'weight'=>'1.73',
                'year'=>'2017',
                'memory'=>'64 Gb',
                'system'=>'Andorid 8.0',
                'processor'=>'Quad-core 2.3 GHz + Quad-core 1.7 GHz',
                'screen'=>'6.2',
                'display'=>'Super AMOLED',
                'resolution'=>'1440 x 2960 pixel',
                'camera'=>'12 Mp',
                'price'=>'450',
                'color' => 'black',
                'status' => 'nuovo',
            ),array(
                'id'=>'3',
                'pic1'=>'../assets/image/catalogotelefoni/samsungj3/1.jpeg',
                'pic2'=>'../assets/image/catalogotelefoni/samsungj3/2.jpeg',
                'pic3'=>'../assets/image/catalogotelefoni/samsungj3/1.jpeg',
                'brand'=>'Samsung',
                'model'=>'J3',
                'weight'=>'1.52',
                'year'=>'2018',
                'memory'=>'16 Gb',
                'system'=>'Andorid 8.0',
                'processor'=>'1.4 GHz Quad Core',
                'screen'=>'5',
                'display'=>'Super AMOLED',
                'resolution'=>'720 x 1280 pixel',
                'camera'=>'8 Mp',
                'price'=>'200',
                'color' => 'black',
                'status' => 'nuovo',
            ),array(
                'id'=>'4',
                'pic1'=>'../assets/image/catalogotelefoni/samsungj5/1.jpeg',
                'pic2'=>'../assets/image/catalogotelefoni/samsungj5/2.jpeg',
                'pic3'=>'../assets/image/catalogotelefoni/samsungj5/3.jpeg',
                'brand'=>'Samsung',
                'model'=>'S9',
                'weight'=>'1.92',
                'year'=>'2018',
                'memory'=>'128 Gb',
                'system'=>'Andorid 8.1',
                'processor'=>'4x 2.8 GHz M3 Mongoose + 4x 1.7 GHz Cortex-A55',
                'screen'=>'5.8',
                'display'=>'Super AMOLED',
                'resolution'=>'1440 x 2960 pixel',
                'camera'=>'12 Mp',
                'price'=>'899',
                'color' => 'black',
                'status' => 'nuovo',
            ),array(
                'id'=>'5',
                'pic1'=>'P10',
                'pic2'=>'P10',
                'pic3'=>'P10',
                'brand'=>'Samsung',
                'model'=>'S9',
                'weight'=>'1.92',
                'year'=>'2018',
                'memory'=>'128 Gb',
                'system'=>'Andorid 8.1',
                'processor'=>'4x 2.8 GHz M3 Mongoose + 4x 1.7 GHz Cortex-A55',
                'screen'=>'5.8',
                'display'=>'Super AMOLED',
                'resolution'=>'1440 x 2960 pixel',
                'camera'=>'12 Mp',
                'price'=>'899',
                'color' => 'black',
                'status' => 'nuovo',
            ),array(
                'id'=>'6',
                'pic1'=>'P10',
                'pic2'=>'P10',
                'pic3'=>'P10',
                'brand'=>'Samsung',
                'model'=>'S9',
                'weight'=>'1.92',
                'year'=>'2018',
                'memory'=>'128 Gb',
                'system'=>'Andorid 8.1',
                'processor'=>'4x 2.8 GHz M3 Mongoose + 4x 1.7 GHz Cortex-A55',
                'screen'=>'5.8',
                'display'=>'Super AMOLED',
                'resolution'=>'1440 x 2960 pixel',
                'camera'=>'12 Mp',
                'price'=>'899',
                'color' => 'black',
                'status' => 'nuovo',
            ),array(
                'id'=>'7',
                'pic1'=>'P10',
                'pic2'=>'P10',
                'pic3'=>'P10',
                'brand'=>'Samsung',
                'model'=>'S9',
                'weight'=>'1.92',
                'year'=>'2018',
                'memory'=>'128 Gb',
                'system'=>'Andorid 8.1',
                'processor'=>'4x 2.8 GHz M3 Mongoose + 4x 1.7 GHz Cortex-A55',
                'screen'=>'5.8',
                'display'=>'Super AMOLED',
                'resolution'=>'1440 x 2960 pixel',
                'camera'=>'12 Mp',
                'price'=>'899',
                'color' => 'black',
                'status' => 'nuovo',
            ),array(
                'id'=>'8',
                'pic1'=>'P10',
                'pic2'=>'P10',
                'pic3'=>'P10',
                'brand'=>'Samsung',
                'model'=>'S9',
                'weight'=>'1.92',
                'year'=>'2018',
                'memory'=>'128 Gb',
                'system'=>'Andorid 8.1',
                'processor'=>'4x 2.8 GHz M3 Mongoose + 4x 1.7 GHz Cortex-A55',
                'screen'=>'5.8',
                'display'=>'Super AMOLED',
                'resolution'=>'1440 x 2960 pixel',
                'camera'=>'12 Mp',
                'price'=>'899',
                'color' => 'black',
                'status' => 'nuovo',
            ),array(
                'id'=>'9',
                'pic1'=>'P10',
                'pic2'=>'P10',
                'pic3'=>'P10',
                'brand'=>'Samsung',
                'model'=>'S9',
                'weight'=>'1.92',
                'year'=>'2018',
                'memory'=>'128 Gb',
                'system'=>'Andorid 8.1',
                'processor'=>'4x 2.8 GHz M3 Mongoose + 4x 1.7 GHz Cortex-A55',
                'screen'=>'5.8',
                'display'=>'Super AMOLED',
                'resolution'=>'1440 x 2960 pixel',
                'camera'=>'12 Mp',
                'price'=>'899',
                'color' => 'black',
                'status' => 'nuovo',
            ),array(
                'id'=>'10',
                'pic1'=>'P10',
                'pic2'=>'P10',
                'pic3'=>'P10',
                'brand'=>'Samsung',
                'model'=>'S9',
                'weight'=>'1.92',
                'year'=>'2018',
                'memory'=>'128 Gb',
                'system'=>'Andorid 8.1',
                'processor'=>'4x 2.8 GHz M3 Mongoose + 4x 1.7 GHz Cortex-A55',
                'screen'=>'5.8',
                'display'=>'Super AMOLED',
                'resolution'=>'1440 x 2960 pixel',
                'camera'=>'12 Mp',
                'price'=>'899',
                'color' => 'black',
                'status' => 'nuovo',
            ),array(
                'id'=>'11',
                'pic1'=>'P10',
                'pic2'=>'P10',
                'pic3'=>'P10',
                'brand'=>'Samsung',
                'model'=>'S9',
                'weight'=>'1.92',
                'year'=>'2018',
                'memory'=>'128 Gb',
                'system'=>'Andorid 8.1',
                'processor'=>'4x 2.8 GHz M3 Mongoose + 4x 1.7 GHz Cortex-A55',
                'screen'=>'5.8',
                'display'=>'Super AMOLED',
                'resolution'=>'1440 x 2960 pixel',
                'camera'=>'12 Mp',
                'price'=>'899',
                'color' => 'black',
                'status' => 'nuovo',
            ),array(
                'id'=>'12',
                'pic1'=>'P10',
                'pic2'=>'P10',
                'pic3'=>'P10',
                'brand'=>'Samsung',
                'model'=>'S9',
                'weight'=>'1.92',
                'year'=>'2018',
                'memory'=>'128 Gb',
                'system'=>'Andorid 8.1',
                'processor'=>'4x 2.8 GHz M3 Mongoose + 4x 1.7 GHz Cortex-A55',
                'screen'=>'5.8',
                'display'=>'Super AMOLED',
                'resolution'=>'1440 x 2960 pixel',
                'camera'=>'12 Mp',
                'price'=>'899',
                'color' => 'black',
                'status' => 'nuovo',
            ),array(
                'id'=>'13',
                'pic1'=>'P10',
                'pic2'=>'P10',
                'pic3'=>'P10',
                'brand'=>'Samsung',
                'model'=>'S9',
                'weight'=>'1.92',
                'year'=>'2018',
                'memory'=>'128 Gb',
                'system'=>'Andorid 8.1',
                'processor'=>'4x 2.8 GHz M3 Mongoose + 4x 1.7 GHz Cortex-A55',
                'screen'=>'5.8',
                'display'=>'Super AMOLED',
                'resolution'=>'1440 x 2960 pixel',
                'camera'=>'12 Mp',
                'price'=>'899',
                'color' => 'black',
                'status' => 'nuovo',
            ),array(
                'id'=>'14',
                'pic1'=>'P10',
                'pic2'=>'P10',
                'pic3'=>'P10',
                'brand'=>'Samsung',
                'model'=>'S9',
                'weight'=>'1.92',
                'year'=>'2018',
                'memory'=>'128 Gb',
                'system'=>'Andorid 8.1',
                'processor'=>'4x 2.8 GHz M3 Mongoose + 4x 1.7 GHz Cortex-A55',
                'screen'=>'5.8',
                'display'=>'Super AMOLED',
                'resolution'=>'1440 x 2960 pixel',
                'camera'=>'12 Mp',
                'price'=>'899',
                'color' => 'black',
                'status' => 'nuovo',
            ),

        ));
    }
}
