<?php

use Illuminate\Database\Seeder;

class SpecificationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('specification')->insert(array(
            array(
                'id'=>'1',
                'pic1'=>'../assets/image/catalogotelefoni/Samsungs9/2.jpeg',
                'pic2'=>'../assets/image/catalogotelefoni/Samsungs9/3.jpeg',
                'pic3'=>'../assets/image/catalogotelefoni/Samsungs9/4.jpeg',
                'pic4'=>'../assets/image/catalogotelefoni/Samsungs9/s9.png',
                'brand'=>'Samsung',
                'model'=>'S9',
                'weight'=>'1.92',
                'year'=>'2018',
                'memory'=>'128 Gb',
                'system'=>'Andorid 8.1',
                'processor'=>'4x 2.8 GHz M3 Mongoose + 4x 1.7 GHz Cortex-A55',
                'screen'=>'5.8',
                'display'=>'Super AMOLED',
                'resolution'=>'1440 x 2960 pixel',
                'camera'=>'12 Mp',
                'price'=>'899',
                'color' => 'black',
                'status' => 'nuovo',
                'qty' => '1',
                'description' => '',
            ),array(
                'id'=>'2',
                'pic1'=>'../assets/image/catalogotelefoni/samsungs8plus/1.jpeg',
                'pic2'=>'../assets/image/catalogotelefoni/samsungs8plus/2.jpeg',
                'pic3'=>'../assets/image/catalogotelefoni/samsungs8plus/3.jpeg',
                'pic4'=>'../assets/image/catalogotelefoni/samsungs8plus/8plus.png',
                'brand'=>'Samsung',
                'model'=>'S8+',
                'weight'=>'1.73',
                'year'=>'2017',
                'memory'=>'64 Gb',
                'system'=>'Andorid 8.0',
                'processor'=>'Quad-core 2.3 GHz + Quad-core 1.7 GHz',
                'screen'=>'6.2',
                'display'=>'Super AMOLED',
                'resolution'=>'1440 x 2960 pixel',
                'camera'=>'12 Mp',
                'price'=>'450',
                'color' => 'black',
                'status' => 'nuovo',
                'qty' => '1',
                'description' => '',
            ),array(
                'id'=>'3',
                'pic1'=>'../assets/image/catalogotelefoni/samsungj3/1.jpeg',
                'pic2'=>'../assets/image/catalogotelefoni/samsungj3/2.jpeg',
                'pic3'=>'../assets/image/catalogotelefoni/samsungj3/1.jpeg',
                'pic4'=>'../assets/image/catalogotelefoni/samsungj3/j3.png',
                'brand'=>'Samsung',
                'model'=>'J3',
                'weight'=>'1.52',
                'year'=>'2018',
                'memory'=>'16 Gb',
                'system'=>'Andorid 8.0',
                'processor'=>'1.4 GHz Quad Core',
                'screen'=>'5',
                'display'=>'Super AMOLED',
                'resolution'=>'720 x 1280 pixel',
                'camera'=>'8 Mp',
                'price'=>'200',
                'color' => 'black',
                'status' => 'nuovo',
                'qty' => '1',
                'description' => '',
            ),array(
                'id'=>'4',
                'pic1'=>'../assets/image/catalogotelefoni/samsungj5/1.jpeg',
                'pic2'=>'../assets/image/catalogotelefoni/samsungj5/2.jpeg',
                'pic3'=>'../assets/image/catalogotelefoni/samsungj5/3.jpeg',
                'pic4'=>'../assets/image/catalogotelefoni/samsungj5/j5.png',
                'brand'=>'Samsung',
                'model'=>'J5',
                'weight'=>'1.58',
                'year'=>'2017',
                'memory'=>'16 Gb',
                'system'=>'Andorid 7.1',
                'processor'=>'1.6 GHz 8 Core',
                'screen'=>'5.2',
                'display'=>'Super AMOLED',
                'resolution'=>'720 x 1280 pixel',
                'camera'=>'13 Mp',
                'price'=>'160',
                'color' => 'black',
                'status' => 'nuovo',
                'qty' => '1',
                'description' => '',
            ),array(
                'id'=>'5',
                'pic1'=>'../assets/image/catalogotelefoni/applei7/1.jpeg',
                'pic2'=>'../assets/image/catalogotelefoni/applei7/2.jpeg',
                'pic3'=>'../assets/image/catalogotelefoni/applei7/3.jpeg',
                'pic4'=>'../assets/image/catalogotelefoni/applei7/7.png',
                'brand'=>'Apple',
                'model'=>'IPhone 7',
                'weight'=>'1.38',
                'year'=>'2016',
                'memory'=>'256 Gb',
                'system'=>'iOS 10',
                'processor'=>'Quad-core',
                'screen'=>'4.7',
                'display'=>'IPS LCD',
                'resolution'=>'750 x 1334 pixel',
                'camera'=>'12 Mp',
                'price'=>'350',
                'color' => 'grey',
                'status' => 'nuovo',
                'qty' => '1',
                'description' => '',
            ),array(
                'id'=>'6',
                'pic1'=>'../assets/image/catalogotelefoni/applei8/1.jpeg',
                'pic2'=>'../assets/image/catalogotelefoni/applei8/2.jpeg',
                'pic3'=>'../assets/image/catalogotelefoni/applei8/3.jpeg',
                'pic4'=>'../assets/image/catalogotelefoni/applei8/8.png',
                'brand'=>'Apple',
                'model'=>'IPhone 8',
                'weight'=>'1.38',
                'year'=>'2018',
                'memory'=>'256 Gb',
                'system'=>'iOS 11',
                'processor'=>'2x Monsoon + 4x Mistral',
                'screen'=>'4.7',
                'display'=>'IPS LCD',
                'resolution'=>'750 x 1334 pixel',
                'camera'=>'12 Mp',
                'price'=>'350',
                'color' => 'black',
                'status' => 'nuovo',
                'qty' => '1',
                'description' => '',
            ),array(
                'id'=>'7',
                'pic1'=>'../assets/image/catalogotelefoni/applei8plus/1.jpeg',
                'pic2'=>'../assets/image/catalogotelefoni/applei8plus/2.jpeg',
                'pic3'=>'../assets/image/catalogotelefoni/applei8plus/3.jpeg',
                'pic4'=>'../assets/image/catalogotelefoni/applei8plus/i8plus.png',
                'brand'=>'Apple',
                'model'=>'IPhone 8+',
                'weight'=>'2.02',
                'year'=>'2018',
                'memory'=>'256 Gb',
                'system'=>'iOS 11',
                'processor'=>'2x Monsoon + 4x Mistral',
                'screen'=>'5.5',
                'display'=>'IPS LCD',
                'resolution'=>'1080 x 1920 pixel',
                'camera'=>'12 Mp + 12 Mp',
                'price'=>'350',
                'color' => 'black',
                'status' => 'nuovo',
                'qty' => '1',
                'description' => '',
            ),array(
                'id'=>'8',
                'pic1'=>'../assets/image/catalogotelefoni/appleiX/1.jpeg',
                'pic2'=>'../assets/image/catalogotelefoni/appleiX/1.jpeg',
                'pic3'=>'../assets/image/catalogotelefoni/appleiX/1.jpeg',
                'pic4'=>'../assets/image/catalogotelefoni/appleiX/x.png',
                'brand'=>'Apple',
                'model'=>'IPhone X',
                'weight'=>'1.74',
                'year'=>'2018',
                'memory'=>'256 Gb',
                'system'=>'iOS 11',
                'processor'=>'2x Monsoon + 4x Mistral',
                'screen'=>'5.8',
                'display'=>'IPS LCD',
                'resolution'=>'4608 x 2592 pixel',
                'camera'=>'12 Mp + 12 Mp',
                'price'=>'900',
                'color' => 'black',
                'status' => 'nuovo',
                'qty' => '1',
                'description' => '',
            ),array(
                'id'=>'9',
                'pic1'=>'../assets/image/catalogotelefoni/huaweip8lite17/1.jpeg',
                'pic2'=>'../assets/image/catalogotelefoni/huaweip8lite17/2.jpeg',
                'pic3'=>'../assets/image/catalogotelefoni/huaweip8lite17/1.jpeg',
                'pic4'=>'../assets/image/catalogotelefoni/huaweip8lite17/p8.png',
                'brand'=>'Huawei',
                'model'=>'P8 Lite',
                'weight'=>'147',
                'year'=>'2018',
                'memory'=>'16 Gb',
                'system'=>'Android 7.0',
                'processor'=>'4x 2.1 GHz Cortex-A53 + 4x 1.7 GHz Cortex-A53',
                'screen'=>'5.2',
                'display'=>'IPS LCD',
                'resolution'=>'1080 x 1920 pixel',
                'camera'=>'12 Mp',
                'price'=>'250',
                'color' => 'black',
                'status' => 'nuovo',
                'qty' => '1',
                'description' => '',
            ),array(
                'id'=>'10',
                'pic1'=>'../assets/image/catalogotelefoni/huaweim10pro/1.jpeg',
                'pic2'=>'../assets/image/catalogotelefoni/huaweim10pro/2.jpeg',
                'pic3'=>'../assets/image/catalogotelefoni/huaweim10pro/3.jpeg',
                'pic4'=>'../assets/image/catalogotelefoni/huaweim10pro/m10.png',
                'brand'=>'Huawei',
                'model'=>'Mate 10 Pro',
                'weight'=>'1.78',
                'year'=>'2018',
                'memory'=>'128 Gb',
                'system'=>'Android 8.0',
                'processor'=>'4x2.4 GHz Cortex-A73 + 4x1.8 GHz Cortex-A53',
                'screen'=>'6',
                'display'=>'AMOLED',
                'resolution'=>'1080 x 2160 pixel',
                'camera'=>'12 Mp',
                'price'=>'550',
                'color' => 'black',
                'status' => 'nuovo',
                'qty' => '1',
                'description' => '',
            ),array(
                'id'=>'11',
                'pic1'=>'../assets/image/catalogotelefoni/huaweip10lite/1.jpeg',
                'pic2'=>'../assets/image/catalogotelefoni/huaweip10lite/1.jpeg',
                'pic3'=>'../assets/image/catalogotelefoni/huaweip10lite/1.jpeg',
                'pic4'=>'../assets/image/catalogotelefoni/huaweip10lite/p10lite.png',
                'brand'=>'Huawei',
                'model'=>'P10 Lite',
                'weight'=>'1.78',
                'year'=>'2017',
                'memory'=>'32 Gb',
                'system'=>'Android 7.0',
                'processor'=>'Quad-core 2.1 GHz Cortex-A53 + Quad-core 1.7 GHz Cortex-A53',
                'screen'=>'5.2',
                'display'=>'IPS LCD',
                'resolution'=>'1080 x 1920 pixel',
                'camera'=>'12 Mp',
                'price'=>'550',
                'color' => 'black',
                'status' => 'nuovo',
                'qty' => '1',
                'description' => '',
            ),array(
                'id'=>'12',
                'pic1'=>'../assets/image/catalogotelefoni/huaweip20/1.jpeg',
                'pic2'=>'../assets/image/catalogotelefoni/huaweip20/1.jpeg',
                'pic3'=>'../assets/image/catalogotelefoni/huaweip20/1.jpeg',
                'pic4'=>'../assets/image/catalogotelefoni/huaweip20/p20.png',
                'brand'=>'Huawei',
                'model'=>'P20',
                'weight'=>'1.65',
                'year'=>'2018',
                'memory'=>'128 Gb',
                'system'=>'Android 8.1',
                'processor'=>'4x2.36 GHz Cortex-A73 + 4x1.84 GHz Cortex-A53',
                'screen'=>'5.8',
                'display'=>'IPS LCD',
                'resolution'=>'1080 x 2244 pixel',
                'camera'=>'12 Mp + 20 Mp',
                'price'=>'550',
                'color' => 'black',
                'status' => 'nuovo',
                'qty' => '1',
                'description' => '',
            ),array(
                'id'=>'13',
                'pic1'=>'../assets/image/catalogotelefoni/huaweip20pro/1.jpeg',
                'pic2'=>'../assets/image/catalogotelefoni/huaweip20pro/2.jpeg',
                'pic3'=>'../assets/image/catalogotelefoni/huaweip20pro/3.jpeg',
                'pic4'=>'../assets/image/catalogotelefoni/huaweip20pro/pro.png',
                'brand'=>'Huawei',
                'model'=>'P20 Pro',
                'weight'=>'1.80',
                'year'=>'2018',
                'memory'=>'128 Gb',
                'system'=>'Android 8.1',
                'processor'=>'4x2.36 GHz Cortex-A73 + 4x1.84 GHz Cortex-A53',
                'screen'=>'6.1',
                'display'=>'OLED',
                'resolution'=>'1080 x 2244 pixel',
                'camera'=>'40 Mp + 20 Mp',
                'price'=>'550',
                'color' => 'black',
                'status' => 'nuovo',
                'qty' => '1',
                'description' => '',
            ),array(
                'id'=>'14',
                'pic1'=>'../assets/image/catalogotelefoni/huwaweip20lite/1.jpeg',
                'pic2'=>'../assets/image/catalogotelefoni/huwaweip20lite/1.jpeg',
                'pic3'=>'../assets/image/catalogotelefoni/huwaweip20lite/1.jpeg',
                'pic4'=>'../assets/image/catalogotelefoni/huwaweip20lite/20lite.png',
                'brand'=>'Huawei',
                'model'=>'P20 Lite',
                'weight'=>'1.45',
                'year'=>'2018',
                'memory'=>'64 Gb',
                'system'=>'Android 8.0',
                'processor'=>'4x 2.36 GHz Cortex-A53 + 4x 1.7 Cortex-A53',
                'screen'=>'5.8',
                'display'=>'IPS LCD',
                'resolution'=>'1080 x 2280 pixel',
                'camera'=>'16 Mp + 2 Mp',
                'price'=>'550',
                'color' => 'black',
                'status' => 'nuovo',
                'qty' => '1',
                'description' => '',
            ),

        ));
    }
}
